baseurl = "http://v-party.de/"
languageCode = "de-de"
title = "V-PARTY"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
description = "v-party website"
author = "räddbiz by langenmaier"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Your description"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "your@email.com"


	# Navigation
	[params.navigation]
		brand = "V-PARTY 03.-04. Juni 2022"
		services = "Party"
		portfolio = "Infos"
		about = "Historie"
		team = "Kontakt"
		contact = "Contact"
		chronic = "Chronik"

  
	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg_1.jpg' in
		# the 'static/img' folder.
		title = "V - PARTY 2022 Zusamaltheim"
		subtitle = "PARTY - TOTAL - ERLEBEN!!!"
		buttonText = "Was gibt's Neues"


	# Services section
	[params.services]
        enable = true
		title = "Party"
		subtitle = "<b>Absage V-Party 2020 & 2021<br><br>Nach dem aktuellen Verbot von Großveranstaltungen bis zum 31.08.2020 trifft es leider nun auch uns. Schweren Herzens müssen wir daher die V-Party am Pfingstwochenende (29. & 30. Mai 2020) absagen. 2020 wird es somit erstmals seit über 20 Jahren keine V-Party geben.<br><br>Nach den großen Erfolgen in den letzten Jahren waren wir bereits seit Monaten in den Vorbereitungen, um für euch wieder ein unvergessliches Event zu organisieren. Wir hatten bereits tolle DJs und Bands für euch gebucht! Leider wird es in diesem Jahr jedoch nicht mögich sein, mit euch gemeinsam wild zu eskalieren.<br><br>Mit Sicherheit war die Entscheidung der zuständigen Behörden und Ämter keine leichte, aber definitiv die Richtige. Die Gesundheit steht nun einfach an erster Stelle! Bleibt zuhause und helft mit, das Virus so schnell wie möglich einzudämmen und dem Ganzen ein Ende zu setzen!<br><br>Das gesamte V-Party-Team blickt dennoch nach vorne! Wir dürfen gerade in dieser schweren Zeit den Humor und die Freude am Leben nicht verlieren und freuen uns jetzt schon auf eine umso größere und schönere V-Party 2021!<br><br>Bleibt stark, seid füreinander da und schützt euch gegenseitig!<br><br>Wir sehen uns auf der V-Party 2021 (Fr, 03.06. & Sa, 04.06.2022)<br><br>Eure V-Party-Crew</b>"

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-music"
                title = "Musik"
                description = "Alle Acts sind auf Grund der Absage wegen der Corona-Pandemie gecancelt! Das für 2020 geplante Programm wäre spektakulär gewesen! Wir hoffen 2022 wieder so ein vielversprechendes Programm für euch auf die Beine stellen zu können..."

            [[params.services.row.list]]
                icon = "fa-cutlery"
                title = "Food"
                description = "Für das leibliche Wohl sorgt der Schützenverein Zusamaltheim mit Pommes, Wurstsalat, Bratwurst- und Schnitzelsemmel. Ein weiterer Verpflegungs-Stand auf der V-Party bietet süße Crepes in verschiedenen Geschmacksrichtungen und Kaffee."

            [[params.services.row.list]]
                icon = "fa-beer"
                title = "Drinks"
                description = "Die Thekenlandschaft fasst auch dieses Jahr wieder über 250m. Die Bar im Zelt, das Weißbierkarusell, die Cocktailbar oder die Stände im Außenbreich laden auch jeden zum gemütlichen Verweilen ein..."

	    [[params.services.row.list]]
                icon = "fa-money"
                title = "Eintritt"
                description = "Kein Einlass unter 18 Jahren!<br />Tickets gibt's nur an der Abendkasse!<br />Vergünstigter Eintritt durch Wochenend-Ticket!<br />Organisiert einen eigenen Bus und bekommt eure Eintrittsbändchen schneller und günstiger!"

	# Portfolio section
	[params.portfolio]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Infos"
		subtitle = "Was muss ich sonst noch wissen?"

		[params.portfolio.modal]
            client = "Client"
            category = "Category"
            buttonText = "zurück"


    # About section
	[params.about]
        enable = true
		title = "Historie"
		subtitle = "Unsere Geschichte"
		endpoint = "V-Party 2022<br>Komm<br>Feier<br>mit Uns!!!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.

		[[params.about.events]]
			img = "Flyer_97.jpg"
			date = "1997"
			title = "Die erste Party steigt im Bauwagen"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_98_1.jpg"
			date = "1998/1"
			title = "Die zweite Party steigt im Bauwagen"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_98_2.jpg"
			date = "1998/2"
			title = "Die dritte Party steigt im Pfannental"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_99.jpg"
			date = "1999"
			title = "Die vierte Party steigt in Sontheim"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_fehlt.jpg"
			date = "2000/1"
			title = "Die fünfte Party steigt auf Böhms Wiese"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_00.jpg"
			date = "2000/2"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_fehlt.jpg"
			date = "2001"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_fehlt.jpg"
			date = "2002"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_03.jpg"
			date = "2003"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_fehlt.jpg"
			date = "2004"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_fehlt.jpg"
			date = "2005"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_fehlt.jpg"
			date = "Fasching 2006"
			title = "Vereinsgründung"
			description = "Die Party wuchs von Jahr zu Jahr und erfreute sich immer höherer Beliebtheit. Um die Party auf geordnete Füße zu stellen wurde 2006 der Verein „Faschingsfreunde Zusamaltheim e.V.“ ins Leben gerufen."

		[[params.about.events]]
			img = "Flyer_fehlt.jpg"
			date = "2007"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_fehlt.jpg"
			date = "2008"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_09.jpg"
			date = "2009"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_10.jpg"
			date = "2010"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_11.jpg"
			date = "2011"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_12.jpg"
			date = "2012"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_13.jpg"
			date = "2013"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_14.jpg"
			date = "2014"
			title = "AAA"
			description = "BBB"

		[[params.about.events]]
			img = "Flyer_15.jpg"
			date = "2015"
			title = "Plötzlicher Umzug"
			description = "Nicht mal plötziche Probleme mit Platz und Untergrund können uns schlagen! Somit sind wir kurzfristig auf einen Nebenplatz umgezogen..."

		[[params.about.events]]
			img = "Flyer_16.jpg"
			date = "2016"
			title = "Auf zum 20. Jubiläum"
			description = "Im Jahr 2016 feiert der „Faschingsfreunde Zusamaltheim e.V.“ sein 10-jähriges Jubiläum! Auf Grund des Unwetters von Freitag Abend musste die Party kurzfristig abgesagt werden. Glücklicherweise konnte dafür am Sonntag nochmal gefeiert werden! Hierfür nochmal herzlichen Dank an alle Beteiligten!<br><a href=\"https:/www.facebook.com/VPartyZusamaltheim/videos/1027099864070390/\" target=\"_blank\">AFTERMOVIE 2016</a><br>test"

	        [[params.about.events]]
			img = "Flyer_17.jpg"
			date = "2017"
			title = "Heißeste Party ever"
			description = "Es wurde getanzt bis der Schweiß von der Decke tropfte! Was für eine Party - welch geile Gäste!!!<br><a href=\"https:/www.youtube.com/watch?v=6RCnBiIPOO8/\" target=\"_blank\">AFTERMOVIE 2017</a>"

                [[params.about.events]]
			img = "Flyer_18.jpg"
			date = "2018"
			title = "Party-Total-Erleben"
			description = "Was für ein Wochenende! Freitag totale Eskalation mit HYPERCAT und DJ Moestwanted und Samstag trotz spätnachmittaglichem Regen und Gewitter PARTY TOTAL ERLEBEN mit DJ EL MAR!!!<br><a href=\"https:/www.youtube.com/watch?v=VXvWYxNn3Og/\" target=\"_blank\">AFTERMOVIE 2018</a>"

		[[params.about.events]]
			img = "Flyer_19.jpg"
			date = "2019"
			title = "2019 = 25. V-Party!!!"
			description = "Wir feiern heuer Jubiläum!!!<br>Wahnsinn!!!"

		[[params.about.events]]
			img = "Corona_2020.jpg"
			date = "2020"
			title = "Absage auf Grund der Corona-Pandemie"
			description = "Die V-Party 2020 musste auf Grund der Corona-Pandemie leider abgesagt werden!"

		[[params.about.events]]
			img = "Corona_2020.jpg"
			date = "2021"
			title = "Absage auf Grund der Corona-Pandemie"
			description = "Die V-Party 2021 musste auf Grund der Corona-Pandemie leider abgesagt werden!"

	# Team section
	[params.team]
        enable = true
		title = "Euer Party Team"
		subtitle = "steht für Fragen und Antworten bereit"
		description = "Traut Euch und schreibt uns einfach auf Facebook, Twitter oder via eMail unter <a href=\"mailto:v-party@gmx.de\" target=\"_blank\">v-party@gmx.de</a> . Wir freuen uns von Euch zu hören! Bis bald..."

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "tobiaslipowsky.jpg"
			name = "Tobias Lipowsky"
			position = "1. Vorstand"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "https://www.facebook.com/tobias.lipowsky"]
			
			]

		[[params.team.members]]
			img = "jonashosemann.jpg"
			name = "Jonas Hosemann"
			position = "Ehemaliger Vorstand"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "https://www.facebook.com/jonas.hosemann"]
			
			]

		[[params.team.members]]
			img = "stefanmayrboeck.jpg"
			name = "Stefan Mayerböck"
			position = "Eventberater Management"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "https://www.facebook.com/stefan.mayrbock"]
			
			]

		[[params.team.members]]
			img = "alexandergerstmayr.jpg"
			name = "Alexander Gerstmayr"
			position = "Technischer Berater & Vorkoster"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "https://www.facebook.com/alex.gonz.180"]
				
			]

		[[params.team.members]]
			img = "rudolfwagner.jpg"
			name = "Rudolf Wagner"
			position = "Website, Chronik, Party"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "https://www.facebook.com/rudi.wagner.779"]
				
			]

	# Client section
    [params.clients_list]
        enable = false

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "envato.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "designmodo.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "themeforest.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "creative-market.jpg"
    		link = "#"





	# Footer section
	[params.footer]
        enable = true
		copyright = "räbbiz by Langenmaier"

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://www.facebook.com/VPartyZusamaltheim/?fref=ts"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "https://www.facebook.com/VPartyZusamaltheim/?fref=ts"		

		[[params.footer.quicklinks]]
			text = "V-Party"
			link = "https://www.facebook.com/VPartyZusamaltheim/?fref=ts"

		[[params.footer.quicklinks]]
			text = "07.-08.06.2019"
			link = "https://www.facebook.com/VPartyZusamaltheim/?fref=ts"
